[TOC]

Runnable的缺陷
1. 无返回值
2. 不能抛出checked Exception

Callabel接口
+ 类似Runnable，被其他线程执行的任务
+ 实现call方法
+ 有返回值

Future
+ 我们可以用Future.get来获取Callable接口返回的执行结果，还可以通过Future.isDone()来判断任务是否已经执行完了，以及取消这个任务，限时获取任务的结果等
+ 在call()未执行完毕之前，调用get()的线程（假定此时是主线程）会被阻塞，直到call()方法返回了结果后，此时future.get()才会得到该结果，然后主线程才会切换到runnable状态
+ 所以Future是一个存储器，它存储了call()这个任务的结果，而这个任务的执行时间是无法提前确定的，因为者完全取决于call()方法执行的情况

Future主要方法
+ get()获取结果
get方法的行为取决于Callable任务的状态，只有以下这5种情况：
1. 任务正常完成：get方法会立刻返回结果
2. 任务尚未完成（任务还没开始或进行中）：get将阻塞并直到任务完成
3. 任务执行过程中抛出Exception：get方法会抛出Exception，这里的抛出异常，是call()执行时产生的那个异常，看到这个异常类型是java.util.concurrent.ExecutionException。不论call()执行时抛出的异常类型是什么，最后get方法抛出的异常类型都是ExecutionException。
4. 任务被取消：get方法会抛出CancellationException
5. 任务超时：get方法有一个重载方法，是传入一个延迟时间的，如果时间到了还没有获得结果，get方法就会抛出TimeoutException。

+ get(long timeout,TimeUnit unit)有超时的获取
用get(long timeout,TimeUnit unit)方法时，如果call()在规定时间内完成了任务，那么就会正常获取到返回值；而如果在指定时间内没有计算出结果，那么就会抛出TimeoutException

+ cancel() 取消任务的执行
1. 如果这个任务还没有开始执行，那么这种情况最简单，任务会被正常的取消，未来也不会被执行，方法返回true
2. 如果任务已完成，或者已取消：那么cancel()方法会执行失败，方法返回false
3. 如果这个任务已经开始执行了，那么这个取消方法将不会直接取消该任务，而是会根据我们填的参数mayInterruptIfRunning做判断

cancel(true)适用于：
1. 任务能够处理interrupt

cancel(false)仅用于避免启动尚未启动的任务，适用于：
1. 未能处理interrupt的任务
2. 不清楚任务是否支持取消
3. 需要等待已经开始的任务执行完成

+ isDone() 判断线程是否执行完毕
+ isCancel() 判断任务是否被取消了

# 用法1：线程池的submit方法返回Future对象
首先，我们要给线程池提交我们的任务，提交时线程池会立刻返回给我们一个空的Future容器。当线程的任务一旦执行完毕，也就是当我们可以获取结果的时候，线程池便会把该结果填入到之前给我们的哪个Future中去（而不是创建一个新的Future），我们此时便可以从该Future中获得任务执行的结果

# 用法2：用FutureTask来创建Future
+ 用FutureTask来获取Future和任务的结果
+ FutureTask是一种包装器，可以把Callable转化成Future和Runnable，它同时实现两者的接口，所以它既可以作为Runnable被线程执行，又可以作为Future得到Callable的返回值
+ 把Callable实例当做参数，生成FutureTask的对象，然后把这个对象当做一个Runnable对象，用线程池或另起线程去执行这个Runnable对象，最后通过FutureTask获取刚才执行的结果

# Future的注意点
+ 当for循环批量获取future的结果时，容易发生一部分线程很慢的情况，get方法调用时应使用timeout限制
+ Future的生命周期不能后退