[TOC]

# 概览
拒绝被中断，这使得它们是不可取消的

# 拒绝终端的方法
下列代码展示了一个方法，该方法等待一个阻塞队列，直到队列中出现一个可用项目，而不管它是否被中断。

为了方便他人，它结束后在一个 finally 块中恢复中断状态，以免剥夺中断请求的调用者的权利。
（它不能在更早的时候恢复中断状态，因为那将导致无限循环 —— BlockingQueue.take()将在入口处立即轮询中断状态，并且，如果发现中断状态集，就会抛出 InterruptedException。）

```java
public Task getNextTask(BlockingQueue<Task> queue) {
    boolean interrupted = false;
    try {
        while (true) {
            try {
                return queue.take();//这发生阻塞了
            } catch (InterruptedException e) {
                interrupted = true;
                // fall through and retry
            }
        }
    } finally {
        if (interrupted)
            Thread.currentThread().interrupt();
    }
}
```
## IO
<font color="red">无响应机制？</font>

并非所有的阻塞方法都抛出InterruptedException。输入和输出流类会阻塞等待I/O完成，但是它们不抛出InterruptedException，而且在被中断的情况下也不会提前返回。然而，对于套接字 I/O，如果一个线程关闭套接字，则那个套接字上的阻塞 I/O 操作将提前结束，并抛出一个 SocketException。

<font color="red">java.nio中的非阻塞I/O类也不支持可中断I/O，但是同样可以通过关闭通道或者请求Selector上的唤醒来取消阻塞操作。</font>

类似地，尝试获取一个内部锁的操作（进入一个synchronized块）是不能被中断的，但是ReentrantLock支持可中断的获取模式。

<font color="red">并不是所有的阻塞都是可中断的, 比如InputStream.read方法. 在检测到输入数据可用, 到达流末尾或者抛出异常前, 该方法一直阻塞. 而且阻塞的时候不会检查中断标记, 所以中断线程无法使read从阻塞状态返回.。但是关闭流可以使得read方法抛出异常, 从而从阻塞状态返回。</font>

例如：
```java
ServerSocket serverSocket = new ServerSocket(PORT);
Socket socket = serverSocket.accept();//阻塞函数
```
Socker.accept()一直在监听端口，一直阻塞在此处。他本身无法响应中断，如果启动一个守护线程来关闭也是可以的：硬关闭，socket.close()

一个情景（伪代码）：
```
method(){
    loop(true){//一直阻塞在此处，永远都走不到下面要执行响应中断的代码
        request()
    }
    while(isInterrupted){
        interrupt()
    }
}
```
## synchronized
synchronized不可被中断，但是wait可以
```java
public class CantInterruptSynchronized {

    static Object obj = new Object();

    public static void main(String[] args) {

        Runnable runnable = ()->{//lumbda创建对象依赖并受限于抽象函数接口
            synchronized (obj){
                System.out.println(Thread.currentThread().getName()+":拿到锁");
                for(;;){
                    System.out.println(Thread.currentThread().isInterrupted());
                }
            }
        };

        Thread thread1 = new Thread(runnable);
        thread1.setName("thread1");
        thread1.start();

        thread1.interrupt();

        Thread thread2 = new Thread(runnable);
        thread2.setName("thread2");
        thread2.start();

    }
}
```
## lock
lock也不行



# try/catch，loop为何会影响中断
java线程中断就是基于try/catch的。interrupt只会更改线程的状态。具体的中断业务代码需要自己写
try/catch在loop中，每次都是单独的一次运行，但是将loop放在try/catch中就不一样了

catch住异常不会中断loop
throw异常可以中断loop
